### PR TITLE
Event quickstart: Fix fields being marked as optional (fixes #3504)

### LINKED ISSUE #3504: Quickstart wizard: required fields marked as optional
### Problem and impact

When choosing "Payment by bank transfer" in the quickstart wizard, the bank detail fields are marked as optional, but are actually required.

### Expected behaviour

Fields are marked as required

### Steps to reproduce

_No response_

### Screenshots

Bildschirmfoto vom 2023-08-03 16-26-24

### Link

_No response_

### Browser (software, desktop or mobile?) and version

_No response_

### Operating system, dependency versions

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by raphaelm**

### CODE REVIEW

File: src/pretix/static/pretixpresale/js/ui/main.js [hunk 1]
```diff
@@ -513,24 +513,24 @@ $(function () {
...
     $("input[data-required-if], select[data-required-if], textarea[data-required-if]").each(function () {
         var dependent = $(this),
-            dependentLabel = $("label[for="+this.id+"]"),
-            dependency = $($(this).attr("data-required-if")),
+            dependencies = $($(this).attr("data-required-if")),
             update = function (ev) {
-                var enabled = (dependency.attr("type") === 'checkbox' || dependency.attr("type") === 'radio') ? dependency.prop('checked') : !!dependency.val();
-                if (!dependent.is("[data-no-required-attr]")) {
-                    dependent.prop('required', enabled);
-                }
```
Comment (luelista) [inline src/pretix/static/pretixpresale/js/ui/main.js:522]: removing this will break the name_parts widget in this configuration:
(it will make optional name parts required)


image



image

Comment (raphaelm) [reply src/pretix/static/pretixpresale/js/ui/main.js:522]: Good catch, this was not intentional, I just tried to sync my changes from pretixcontrol to pretixpresale and missed this

File: src/pretix/static/pretixcontrol/js/ui/main.js [hunk 2]
```diff
@@ -415,16 +415,25 @@ var form_handlers = function (el) {
...
         var dependent = $(this),
-            dependency = $($(this).attr("data-required-if")),
+            dependencies = $($(this).attr("data-required-if")),
             update = function (ev) {
-                var enabled = (dependency.attr("type") === 'checkbox' || dependency.attr("type") === 'radio') ? dependency.prop('checked') : !!dependency.val();
+                var enabled = true;
+                dependencies.each(function () {
+                    var dependency = $(this);
+                    var e = (dependency.attr("type") === 'checkbox' || dependency.attr("type") === 'radio') ? dependency.prop('checked') : !!dependency.val();
+                    console.log(dependent, dependency, e)
```
Comment (luelista) [inline src/pretix/static/pretixcontrol/js/ui/main.js]:
```suggestion
```
